
<form id="resetForm" method="post" action='index.php' enctype="multipart/form-data">
	
	<!-- view all JSON button -->

	<span>Power Buttons!</span>

	<br>
	<!-- delete JSON button -->
	<span>			
		<input type="submit" name="resetJSON" class="powerButton" value="Reset JSON" />
	</span> 
	
	<!-- delete all the images inside the upload folder -->
	<span>			
		<input type="submit" name="deleteAllEntries" class="powerButton" value="Delete All Entries" />
	</span> 
	
	<!-- delete the all UID -->
	<span>			
		<input type="submit" name="deleteUID" class="powerButton" value="Delete All UID" />
	</span> 
	
</form>
